version: '3'
services:
  cassandra:
    image: cassandra
    ports: 
      - 9042:9042
  kafka:
    depends_on: 
      - zookeeper
    image: confluentinc/cp-kafka
    ports: 
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - host
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports: 
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - host
  kafkarest:
    image: confluentinc/cp-kafka-rest
    depends_on: 
      - kafka
      - zookeeper
    ports: 
      - 8082:8082
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_HOST_NAME: kafkarest
    networks:
      - host
  schemareg:
    image: confluentinc/cp-schema-registry
    depends_on: 
      - kafka
      - zookeeper
    ports: 
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schemareg
    networks:
      - host
networks:
  host: